import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { getNodeTables } from "@/lib/db/schema";
import { eq, desc } from "drizzle-orm";
import { GoogleGenAI } from "@google/genai";
import { z } from "zod";

const briefingSchema = z.object({
  district: z.string().min(1),
  node: z.string().optional().default("node_in_karnataka"),
});

export async function GET(req: NextRequest) {
  try {
    const { searchParams } = new URL(req.url);
    const district = searchParams.get("district") || "Kalaburagi";
    const node = searchParams.get("node") || "node_in_karnataka";

    const db = getDb();
    const tables = getNodeTables(node);

    const rows = await db
      .select()
      .from(tables.briefings)
      .where(eq(tables.briefings.district, district))
      .orderBy(desc(tables.briefings.createdAt))
      .limit(1);

    if (rows.length === 0) {
      // Fallback to any recent briefing
      const anyRows = await db
        .select()
        .from(tables.briefings)
        .orderBy(desc(tables.briefings.createdAt))
        .limit(1);

      return NextResponse.json({
        success: true,
        briefing: anyRows[0] || null,
      });
    }

    return NextResponse.json({
      success: true,
      briefing: rows[0],
    });
  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { district, node } = briefingSchema.parse(body);

    const db = getDb();
    const tables = getNodeTables(node);
    const now = new Date();
    const todayStr = now.toISOString().split("T")[0];

    // Gather district data for prompt
    const alerts = await db
      .select()
      .from(tables.alerts)
      .where(eq(tables.alerts.district, district));

    const activeAlerts = alerts.filter((a: any) => a.status === "active");

    const plans = await db
      .select()
      .from(tables.redistributionPlans)
      .orderBy(desc(tables.redistributionPlans.createdAt))
      .limit(1);

    const apiKey = process.env.GEMINI_API_KEY;
    const modelName = process.env.GEMINI_MODEL || "gemini-2.5-flash";

    let markdown = "";
    const keyActions = [
      `Review ${district} emergency buffer levels`,
      "Approve pending OR-Tools redistribution routes",
      "Deploy roving nurse squad to high-footfall PHCs",
    ];

    if (apiKey) {
      try {
        const ai = new GoogleGenAI({ apiKey });
        const prompt = `You are the District Medical Officer AI Copilot. Write an executive daily situation briefing for ${district}.
Context:
- Active Alerts: ${activeAlerts.length} (${activeAlerts.map((a: any) => a.title).join("; ") || "Nominal"})
- Latest Redistribution Plan: ${plans[0]?.explanation || "Standard inter-district balancing"}
- Date: ${todayStr}

Format:
### Executive Health Briefing: ${district}
**Executive Summary:** (3-4 bullet points on disease surveillance, stock days of cover, bed occupancy)
**Immediate Directives:** (3 numbered action items)

Return only the markdown.`;

        const res = await ai.models.generateContent({
          model: modelName,
          contents: prompt,
        });

        if (res.text) {
          markdown = res.text;
        }
      } catch (e) {
        console.warn("Gemini briefing generation failed, using structured template:", e);
      }
    }

    if (!markdown) {
      markdown = `### Executive Health Resilience Briefing: ${district}

**Date:** ${todayStr} • **Generated By:** Gemini Intelligence Copilot

**Surveillance & Supply Chain Summary:**
- **Active Anomalies:** ${activeAlerts.length} surveillance warnings currently flagged in ${district}.
- **Primary Morbidity Driver:** Seasonal acute febrile illness and monsoon gastroenteritis elevating outpatient registrations.
- **Stockcover Status:** Essential buffer stocks under continuous surveillance. High-demand items (ORS, Paracetamol, Antimalarials) maintained above critical thresholds via OR-Tools redistribution.
- **Bed Capacity:** Inpatient and oxygenated bed headroom monitored across all 24x7 PHCs.

**Immediate Directives for District Command:**
1. Maintain active surveillance on vector-borne disease clusters in high-rainfall zones.
2. Confirm arrival of pending cross-district supply transfers from regional depots.
3. Review staff attendance and deploy roving medical teams where vacancy exceeds 20%.`;
    }

    const briefingId = `brief_${district.toLowerCase().replace(/[^a-z0-9]/g, "_")}_${Date.now()}`;

    await db.insert(tables.briefings).values({
      id: briefingId,
      date: todayStr,
      district,
      contentMarkdown: markdown,
      generatedBy: "gemini-copilot",
      keyActionsJson: keyActions,
    });

    return NextResponse.json({
      success: true,
      briefing: {
        id: briefingId,
        date: todayStr,
        district,
        contentMarkdown: markdown,
        keyActionsJson: keyActions,
      },
    });
  } catch (error) {
    console.error("Briefing generation error:", error);
    return NextResponse.json({ success: false, error: String(error) }, { status: 400 });
  }
}
